In [1]:
import pandas as pd
import numpy as np

In [2]:
lst = [5,10,15,20,25]
lst

[5, 10, 15, 20, 25]

In [3]:
lst.append(30) # add at the end of list
lst

[5, 10, 15, 20, 25, 30]

In [4]:
lst.extend([35,40]) # adds elements of another list to the end
lst

[5, 10, 15, 20, 25, 30, 35, 40]

In [5]:
lst.insert(-1,45) # add element to index
lst

[5, 10, 15, 20, 25, 30, 35, 45, 40]

In [6]:
lst.remove(45) # remove the first occurance of element or value
lst

[5, 10, 15, 20, 25, 30, 35, 40]

In [7]:
lst.pop(2) # remove the value in given index
lst

[5, 10, 20, 25, 30, 35, 40]

In [9]:
lst.index(30) # give the index of value in the list

4

In [11]:
lst.count(15) # return number of time value come

0

In [13]:
lst.sort() # Sort list (ascending order)
lst

[5, 10, 20, 25, 30, 35, 40]

In [14]:
lst.reverse() # give list in reverse order
lst

[40, 35, 30, 25, 20, 10, 5]

In [17]:
lst.clear() # clear the values in the list
lst

[]

In [18]:
std = ("Chandan","Anil","Neha")
std

('Chandan', 'Anil', 'Neha')

In [19]:
std[0] = "Rekha" # immutable (elements cannot be modified, added, or removed)

TypeError: 'tuple' object does not support item assignment

In [20]:
s = {1,5,2,4,5,3,6,}
s   # remove the duplicate values and sort the list

{1, 2, 3, 4, 5, 6}

In [26]:
dic = {'Name':'Chandan',
       'Age': 36,
       'City':'Shimla'}
dic

{'Name': 'Chandan', 'Age': 36, 'City': 'Shimla'}

In [29]:
dic['Age'] = 35 # update the age
dic

{'Name': 'Chandan', 'Age': 35, 'City': 'Shimla'}

In [31]:
dic['email'] = 'chandanchandel@gmail.com' # update the new key email in the dictionary
dic

{'Name': 'Chandan',
 'Age': 35,
 'City': 'Shimla',
 'email': 'chandanchandel@gmail.com'}

In [38]:
age = int(input(f"Enter your age = "))
if age >= 18:
    print('*'*40)
    print(f"You are eligible to cast vote")
    print('*'*40)
else:
    print('*'*40)
    print(f"You are not eligible to cast vote")
    print('*'*40)

Enter your age =  17


****************************************
You are not eligible to cast vote
****************************************


In [141]:
marks = float(input(f"Enter Your marks : "))
def grade(marks):
    if marks >= 90:
        print(f"Your grade is A")
    elif marks >= 75 and marks <= 89:
        print(f"Your grade is B")
    elif marks >= 50 and marks <= 74:
        print(f"Your grade is C")
    else:
        print(f"Your are Fail")
grade(marks)

Enter Your marks :  56


Your grade is C


In [73]:
n = float(input(f"Enter any Number : "))
if n > 0:
    if n % 2 == 0:
        print(f"The number is positive and even")
    else:
        print(f"The number is positive and odd")
elif n == 0:
    print(f"The number is zero")
else:
    print(f"The number is negative")

Enter any Number :  17


The number is positive and odd


In [88]:
arr = np.array(5)
arr1 = np.arange(1,6)
arr2 = np.arange(10,70,10).reshape(2,3)
print(f"A scalar : ",arr)
print(f"A 1D array : ",arr1)
print(f"2D array (2x3) : ",arr2)

A scalar :  5
A 1D array :  [1 2 3 4 5]
2D array (2x3) :  [[10 20 30]
 [40 50 60]]


In [92]:
array = np.random.randint(0,100, size=(4,4))
array

array([[31, 11, 31, 27],
       [18,  1, 28,  0],
       [ 9, 25, 92, 10],
       [41, 85, 67, 32]], dtype=int32)

In [95]:
t = np.random.randint(0,10, size=(3,3))
df = pd.DataFrame(t, columns=['A','B','C'])
print(f"Numpy Array : ")
print(t)
print(f" Dataframe : ")
print(df)

Numpy Array : 
[[2 5 9]
 [5 4 1]
 [9 3 3]]
 Dataframe : 
   A  B  C
0  2  5  9
1  5  4  1
2  9  3  3


In [134]:
data = {
        'Name' : ['Chandan','Anil','Rajesh','Manu','Chandan','Sonu','Nishu','Pankaj','Rahul','Raju'],
        'Age' : [45,40,62,55,45,48,75,12,34,65],
        'City' : ['Shimla','Kullu','Manali','Chandigarh','Shimla','Delhi','Manesar','Dharamshala','Kanpur','Jaipur'],
        'Salary' : [45000,65000,35621,16000,45000,56024,42651,35621,89731,69421]
}
df = pd.DataFrame(data)
df

Name  Age         City  Salary
0  Chandan   45       Shimla   45000
1     Anil   40        Kullu   65000
2   Rajesh   62       Manali   35621
3     Manu   55   Chandigarh   16000
4  Chandan   45       Shimla   45000
5     Sonu   48        Delhi   56024
6    Nishu   75      Manesar   42651
7   Pankaj   12  Dharamshala   35621
8    Rahul   34       Kanpur   89731
9     Raju   65       Jaipur   69421

In [125]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    10 non-null     object
 1   Age     10 non-null     int64 
 2   City    10 non-null     object
 3   Salary  10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes


In [135]:
df.describe()

Age        Salary
count  10.000000     10.000000
mean   48.100000  50006.900000
std    17.754186  20791.383859
min    12.000000  16000.000000
25%    41.250000  37378.500000
50%    46.500000  45000.000000
75%    60.250000  62756.000000
max    75.000000  89731.000000

In [127]:
col = df[['Name','City']] #Select 'Name' and 'City' columns
col

Name         City
0  Chandan       Shimla
1     Anil        Kullu
2   Rajesh       Manali
3     Manu   Chandigarh
4    Priya       Mumbai
5     Sonu        Delhi
6    Nishu      Manesar
7   Pankaj  Dharamshala
8    Rahul       Kanpur
9     Raju       Jaipur

In [128]:
drop_city = df.drop(columns = ['City']) # remove column City
drop_city

Name  Age  Salary
0  Chandan   45   45000
1     Anil   40   65000
2   Rajesh   62   35621
3     Manu   55   16000
4    Priya   25  164222
5     Sonu   48   56024
6    Nishu   75   42651
7   Pankaj   12   35621
8    Rahul   34   89731
9     Raju   65   69421

In [129]:
df['Salary'].isnull() # missing value

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: Salary, dtype: bool

In [130]:
sal_mean = df['Salary'].mean() # mean of salary
sal_mean

np.float64(61929.1)

In [136]:
df['Salary'].fillna(sal_mean)

0    45000
1    65000
2    35621
3    16000
4    45000
5    56024
6    42651
7    35621
8    89731
9    69421
Name: Salary, dtype: int64

In [137]:
df.drop_duplicates() #Remove any duplicate rows

Name  Age         City  Salary
0  Chandan   45       Shimla   45000
1     Anil   40        Kullu   65000
2   Rajesh   62       Manali   35621
3     Manu   55   Chandigarh   16000
5     Sonu   48        Delhi   56024
6    Nishu   75      Manesar   42651
7   Pankaj   12  Dharamshala   35621
8    Rahul   34       Kanpur   89731
9     Raju   65       Jaipur   69421